id = "openmoji-icons"
name = "OpenMoji Emoji Icons Theme"
version = "0.2.0"
schema_version = 1
authors = ["Coty Hamilton"]
description = "OpenMoji emoji icons"
repository = "https://github.com/cotyhamilton/zed-emoji-icon-theme.git"
